### ISSUE TITLE
Service Provider not found

### ISSUE THREAD

**Issue by shivergard** [Saritasa/php-laravel-chat-api#1]
[Symfony\Component\Debug\Exception\FatalThrowableError]        
  Class 'Saritasa\LaravelChatApi\ChatServiceProvider' not found

Laravel Framework 5.5.13

composer.json
`"saritasa/laravel-chat-api": "^1.0"`

**Comment by veeeeeRySeXy** [comment]
Yes you right. There was an issue in old version. Version 2.0 require minimum laravel version 5.5 and uses package auto-discovery. I will close this issue.
