### ISSUE TITLE
Laravel version

### ISSUE THREAD

**Issue by 123maher** [Saritasa/php-laravel-chat-api#4]
Hi, just wonderng why Laravel 54 is not supported in v2.0 ? Is it just because of package auto discovery ?

**Comment by 123maher** [comment]
Hi, just wonderng why Laravel 54 is not supported in v2.0 ? Is it just because of package auto discovery ?

**Comment by veeeeeRySeXy** [comment]
Hi. All projects were it was used was 5.5 version, so we didn't think about support 5.4 or lower. If it really necessary for you we are open to pull requests :+1:
